# Generated by Django 4.2.20 on 2025-06-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0002_alter_borrowrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='return_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('return_requested', 'Return Requested'), ('return_rejected', 'Return Rejected')], default='pending', max_length=20),
        ),
    ]
