# Generated by Django 4.2.20 on 2025-06-01 11:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_type', models.CharField(choices=[('physical', 'Physical Book'), ('electronic', 'Electronic Book')], default='physical', max_length=10)),
                ('location_code', models.CharField(blank=True, max_length=20, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='books/electronic/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'epub', 'mobi'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='management', to='books.book')),
            ],
        ),
    ]
