# Generated by Django 5.1.7 on 2025-05-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmanagement",
            name="book_type",
            field=models.CharField(
                choices=[
                    ("physical", "Physical Book"),
                    ("electronic", "Electronic Book"),
                ],
                default="physical",
                max_length=10,
            ),
        ),
    ]
