# Generated by Django 5.1.7 on 2025-05-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="agree_terms",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="contact_number",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="membership_type",
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
    ]
